### ISSUE TITLE
Same as #37 and #38

### ISSUE THREAD

**Issue by jpobeda** [Cacti/plugin_mactrack#39]
I can't re open issues I didn't close.

Issue still the same...

Now if you fix the extra comma here..takes us to #38

```
2017/09/24 13:35:13 - CMDPHP ERROR: A DB Exec Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE ip_range = 'xxx.yy.78' AND site_id = '10'' at line 1
2017/09/24 13:35:13 - DBCALL ERROR: A DB Exec Failed!, Error:1064, SQL:'UPDATE mac_track_ip_ranges SET ips_current = ?, ips_current_date = ?, WHERE ip_range = ? AND site_id = ?'
2017/09/24 13:35:13 - CMDPHP ERROR: A DB Exec Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE ip_range = 'xxx.yy.76' AND site_id = '1'' at line 1
2017/09/24 13:35:13 - DBCALL ERROR: A DB Exec Failed!, Error:1064, SQL:'UPDATE mac_track_ip_ranges SET ips_current = ?, ips_current_date = ?, WHERE ip_range = ? AND site_id = ?'
2017/09/24 13:35:13 - CMDPHP ERROR: A DB Exec Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE ip_range = 'xxx.yy.75' AND site_id = '1'' at line 1
2017/09/24 13:35:13 - DBCALL ERROR: A DB Exec Failed!, Error:1064, SQL:'UPDATE mac_track_ip_ranges SET ips_current = ?, ips_current_date = ?, WHERE ip_range = ? AND site_id = ?'
2017/09/24 13:35:13 - CMDPHP ERROR: A DB Exec Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE ip_range = 'xxx.yy.66' AND site_id = '2'' at line 1
2017/09/24 13:35:13 - DBCALL ERROR: A DB Exec Failed!, Error:1064, SQL:'UPDATE mac_track_ip_ranges SET ips_current = ?, ips_current_date = ?, WHERE ip_range = ? AND site_id = ?'
2017/09/24 13:35:13 - CMDPHP ERROR: A DB Exec Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE ip_range = 'xxx.yy.30' AND site_id = '7'' at line 1
2017/09/24 13:35:13 - DBCALL ERROR: A DB Exec Failed!, Error:1064, SQL:'UPDATE mac_track_ip_ranges SET ips_current = ?, ips_current_date = ?, WHERE ip_range = ? AND site_id = ?'
2017/09/24 13:35:13 - CMDPHP ERROR: A DB Exec Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE ip_range = 'xxx.yy.27' AND site_id = '3'' at line 1
2017/09/24 13:35:13 - DBCALL ERROR: A DB Exec Failed!, Error:1064, SQL:'UPDATE mac_track_ip_ranges SET ips_current = ?, ips_current_date = ?, WHERE ip_range = ? AND site_id = ?'
2017/09/24 13:35:13 - CMDPHP ERROR: A DB Exec Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE ip_range = 'xxx.yy.22' AND site_id = '6'' at line 1
2017/09/24 13:35:13 - DBCALL ERROR: A DB Exec Failed!, Error:1064, SQL:'UPDATE mac_track_ip_ranges SET ips_current = ?, ips_current_date = ?, WHERE ip_range = ? AND site_id = ?'
2017/09/24 13:35:13 - CMDPHP ERROR: A DB Exec Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE ip_range = 'xxx.yy.130' AND site_id = '3'' at line 1
2017/09/24 13:35:13 - DBCALL ERROR: A DB Exec Failed!, Error:1064, SQL:'UPDATE mac_track_ip_ranges SET ips_current = ?, ips_current_date = ?, WHERE ip_range = ? AND site_id = ?'
2017/09/24 13:35:13 - CMDPHP ERROR: A DB Exec Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE ip_range = 'xxx.yy.129' AND site_id = '4'' at line 1
2017/09/24 13:35:13 - DBCALL ERROR: A DB Exec Failed!, Error:1064, SQL:'UPDATE mac_track_ip_ranges SET ips_current = ?, ips_current_date = ?, WHERE ip_range = ? AND site_id = ?'
2017/09/24 13:35:13 - CMDPHP ERROR: A DB Exec Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE ip_range = 'xxx.yy.129' AND site_id = '3'' at line 1
2017/09/24 13:35:13 - DBCALL ERROR: A DB Exec Failed!, Error:1064, SQL:'UPDATE mac_track_ip_ranges SET ips_current = ?, ips_current_date = ?, WHERE ip_range = ? AND site_id = ?'
2017/09/24 13:35:13 - CMDPHP ERROR: A DB Exec Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE ip_range = 'xxx.yy.128' AND site_id = '3'' at line 1
2017/09/24 13:35:13 - DBCALL ERROR: A DB Exec Failed!, Error:1064, SQL:'UPDATE mac_track_ip_ranges SET ips_current = ?, ips_current_date = ?, WHERE ip_range = ? AND site_id = ?'
```

**Comment by jpobeda** [comment]
And please, wait for feedback before closing the issue. It doesn't make sense to open 3 issues for the same thing.

**Comment by jpobeda** [comment]
I haven't seen this commit 54533366ce391ef39911cdf4a90ff47fa4d1fa27. I'll test it, please don't close it.

**Comment by jpobeda** [comment]
Alright so poller_mactrack.php line 737. There is one issue.

```
 735                                         db_execute_prepared('UPDATE mac_track_ip_ranges
    736                                                 SET ips_current = ?,
    737                                                 ips_current_date = ?,
    738                                                 WHERE ip_range = ?
    739                                                 AND site_id = ?',
    740                                                 array(
    741                                                         $ip_range['ips_current'],
    742                                                         $ip_range['ips_current_date'],
    743                                                         $range_record['ip_range'],
    744                                                         $range_record['site_id']
    745                                                 )
```

Once I remove that "comma" I  get

`2017/09/25 10:19:19 - MACTRACK ERROR: Can not start MAC Tracking process. There is already one in progress`

So it looks like now I'm not getting the SQL empty error due to this commit https://github.com/Cacti/plugin_mactrack/commit/54533366ce391ef39911cdf4a90ff47fa4d1fa27

All functions seem to be working fine so I guess the only remaining issue is the ambiguous message:

`2017/09/25 10:19:19 - MACTRACK ERROR: Can not start MAC Tracking process. There is already one in progress`

**Comment by jpobeda** [comment]
Furthermore, the message "MACTRACK ERROR: Can not start MAC Tracking process. There is already one in progress" doesn't show up on every run which made me think about it.

So I took a few samples from the logs when I got that ERROR.

2017-09-25 14:00:54 = $start_date = 1506300653
2017/09/25 14:01:45 = time() = 1506300703
max_run_duration = 600 - 60 = 540

So i should get this error if $start_date > time() - 540 

Which I'd probably always get when running cacti's poller at 1 min interval. 

What do you think?

**Comment by cigamit** [comment]
I'll look at this again once I review your other changes.

**Comment by jpobeda** [comment]
I fixed the comma on https://github.com/Cacti/plugin_mactrack/pull/40 but I'd like you to review the whole scan timer check for 1 min polling interval.

**Comment by jpobeda** [comment]
@netniV 

Do you feel like helping on this one as well :D?

**Comment by netniV** [comment]
I should charge you for this 😈 

I'll add it to my list for the week.  But do bear in mind that I don't actually use this plugin so I am never totally sure it's working 🌵

**Comment by jpobeda** [comment]
Oh c'mon that's not the spirit lol
I'm happy to test it for you. If you need some background about this, here we go:

The issue at this point is only regarding the message
"MACTRACK ERROR: Can not start MAC Tracking process. There is already one in progress"

As I understand cacti's poller calls every file starting with poller_ so the login to check whether it needs to run or not seems to have been written for 5 min poller interval.

So if you're running 1 min interval, it will call poller_mactrack every time and check if needs to run or not and sometimes, when mactrack takes long enough to run it seems to hit this condition where it checks if it should run or not even though you configure under settings mactrack poller interval to something like 30 min, once a day or whatever.

I got confused already so fire up your questions when you're ready.

**Comment by netniV** [comment]
I was just kidding.  I've slightly reviewed what's in the code, but you are correct I have questions especially as the message about the process already being in progress seems correct to me, as it is in the following scenarios:


Poller Interval | Start Time | Current Time | Max Run | Warn if Running 
--- | --- | --- | --- | ---
60 Seconds | 03:00 | 03:01 | 300 | (3:01 - 300s) = 2:56 <= 3:01
60 Seconds | 03:00 | 03:01 | 60 | (3:01 - 60s) = 3:00 <= 301

The problem is that the mactrack poller is still running when the cacti poller attempts to run it again.  And, it's allowed to be running still.

So I guess your saying that it should be updated to be more:

Poller Interval | Start Time | Current Time | Max Run | Warn if Running 
--- | --- | --- | --- | ---
60 Seconds | 03:00 | 03:01 | 300 | (3:00 + 300s) = 3:05 <= 3:01
60 Seconds | 03:00 | 03:01 | 60 | (3:00 + 60s) = 3:01 <= 301

This changes the formula from

- start_date > (time() - $max_run_duration) 
   to
- start_date + max_run_duration < time()

Correct? All I'm planning on doing here is affecting the warning, it does not cause another mactrack poller to actually run.

**Comment by jpobeda** [comment]
Yep, that's it I think.  

<3

**Comment by netniV** [comment]
OK, well I'm being a bit cautious about this because that same field is used a lot for different time checks. There is also a stale check, which assumes older processes are no longer in use (although in reality there could actually be one or more really over running processes!)

**Comment by cigamit** [comment]
Bah, my head is about to explode.

**Comment by jpobeda** [comment]
@netniV have you dropped the ball on this one :'(  ?

**Comment by netniV** [comment]
No, just being careful.  Like I said, there are different things happening around that code so I'm giving myself time to re-read it and make sure I come to the same conclusion since it's a core part of getting MT to run! 👍

**Comment by netniV** [comment]
So I have got a lot more familiar with this code tonight by trying to implement my own scanning function for the HPE OfficeConnect 1920.  So, over the weekend, I should be able to have a look at this and see what's going on.  However, I'm not so sure the part we looked at is wrong, but i'll give more of an update when I look properly.

**Comment by netniV** [comment]
So here is the low down on why this error occurs. 

1. Poller starts up doing it's time checks.
   1. If a `mac_track_process` entry exists, check when it was started
   2. Spawn off mactrack_scanner.php up to a maximum of `mt_processes` passing a device id
   3. As a process becomes free, repeat step 2 until all devices are complete.
   4. If DNS resolution is needed, spawn off an extra background process
2. When mactrack_scanner.php starts
   1. Verify parameters
   2. If we aren't running in test mode, use db_process_add() to add a new entry to `mac_track_process` with the device id or 0 if DNS process
   3. Do the various scans.

Now, the issue comes that the lowest scan time is that the earliest scan time is used from `mac_track_process` to work out whether it is still running.  I think that if an error occurs, that table doesn't get cleared out properly.  But I would need to check further if an error handler has been installed to remove the entry if present.

One thing that I did notice, db_process_add() doesn't add the pid on every insert for some reason.  Not sure on the logic behind that. Maybe @cigamit  or @TheWitness  may have more knowledge as to why.  I think if we changed that process id to be always populated, we could track back to which one failed.  Either way, I think looking at the entries of that table when this error occurs would show what's going on.

**Comment by netniV** [comment]
Been working on other plugins, but I'll try to get back to this over the next week or two.

**Comment by cigamit** [comment]
Can you please update to the latest release.  A lot of things have been fixed.  If you still have issues, open a new ticket.

**Comment by jdcoats** [comment]
> The issue at this point is only regarding the message
"MACTRACK ERROR: Can not start MAC Tracking process. There is already one in progress"

This issue does still exist. It doesn't cause a problem. It just makes red marks in your clean green log :)
It is seen when using a 1 minute polling interval. The error is seen every minute that mactrack is running. 
![untitled](https://user-images.githubusercontent.com/42470924/53175070-4129ef80-35b9-11e9-9047-0d10a80528c5.png)
I guess I could just change it to be a system message instead of an error since it has always been there. This issue has existed since the 1st versions of mactrack i think.

**Comment by jpobeda** [comment]
@jdcoats, Now it's on your hand to create a new issue. Call it Same as#37, #38 and #39 lol
